# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-21 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='海南水司调峰系统', max_length=30)),
                ('phone_number', models.CharField(default='13000000000', max_length=18)),
                ('address', models.CharField(default='上海', max_length=20)),
                ('account', models.CharField(default='admin', max_length=20)),
                ('password', models.CharField(default='123456', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='item_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name_detail', models.CharField(default='场景模拟', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='problem_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_sort_detail', models.CharField(default='分', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='problem_sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_sort_name', models.CharField(default='全局问题', max_length=10)),
            ],
        ),
    ]
